Add autoFill and highlightOnFocus as directive options
aguirrel/ng-currency pull request #139
Opened 2017-05-04 14:53 UTC by turt2live

The readme claims that displayZeros is supported, but does not work. This adds a useful alternative to displayZeros through two options: autoFill and highlightOnFocus.

autoFill simply populates the field with `0` if there has been no number entered. This is done before formatting takes place just in case something needs to happen (such as the result being `0.00`). This also occurs before the minimum is considered, so that the minimum can be applied to autoFill.

highlightOnFocus addresses #118 and is enabled by default. This is to make entering a large number of fields easier for the user, and just generally make the field more usable.

2017-05-04 14:56 UTC, turt2live commented
Looks like I blew up the tests (something that doesn't happen on my end). Will take a look.

2017-05-04 16:01 UTC, cecilia-sanare requested changes
Thanks for your contribution @turt2live!

Overall your changes look good, just a couple of issues I noticed.

2017-05-04 16:01 UTC, nick-woodward commented on test/ng-currency/ng-currency-settings.provider.spec.js
> +        highlightOnFocus: true
Rather then reusing tests for other bindings can you add a separate group for testing `highlightOnFocus` and `autoFill`.

2017-05-04 16:01 UTC, nick-woodward commented on src/ng-currency.directive.js
> +            controller.$$rawModelValue = '0';
This makes it so once the user focuses the field the value is populated with zero (if its empty and autoFill is enabled).

Instead we should prepopulate it with zero.

2017-05-09 17:21 UTC, cecilia-sanare requested changes
I really like how you utilized `revalidate` to handle the `auto-fill`.

Once you resolve the final issue this PR should be good to go! :+1:

2017-05-09 17:21 UTC, nick-woodward commented on src/ng-currency.directive.js
> +            controller.$$rawModelValue = '0';
One thing I noticed with this solution is that the value never gets commited to the `modelValue`.

Instead can you move this logic to the top of the `keepInRange` function. That way the if statement below gets executed.

```js
function keepInRange(value) {
  if (autoFill && [undefined, null, ''].indexOf(value) !== -1) {
    value = 0;
  }
  // ...
}
```

2017-05-09 17:21 UTC, nick-woodward commented on test/ng-currency/ng-currency.directive.spec.js
> +    describe('AutoFill', () => {
Please validate the `scope.value` as well.

2017-05-09 17:29 UTC, turt2live commented
I'm also looking to add tri-state support to autoFill, as the original behaviour (on focus) is what we were using before in our own fork. Thoughts on having `autoFill` be `true`, `false`, or `focus`?

2017-05-09 17:35 UTC, nick-woodward commented
Sounds good to me!

2017-05-16 01:58 UTC, turt2live commented
@nick-woodward apologies for the long delay in getting updates through. This should now be complete.

Here's the rundown on how it's supposed to work (backed up by the tests):
* `autoFill` can be `true`, `false`, or `focus`
  * `true` - Pre-populate the field with `0` (bound by the min/max) on init
  * `false` - Default behaviour, do nothing different.
  * `focus` - Only pre-populate the field with `0` (bound by the min/max) on focus. Value intentionally retained on blur
* `highlightOnFocus` - Select the entire value on focus. Ideal for "quick edit" styled forms.

2018-03-14 20:29 UTC, turt2live commented
Unfortunately my spare time is limited and the project that was using this library doesn't need this patch any more. Going to have to close this :(

2018-03-14 20:29 UTC, closed without merging